"""Tests for the systemd *user* service generated by `wt install` on Linux.

Parallel to test_launchagent_plist.py, these lock in the same three reliability
guarantees for the systemd unit:
  1. Restart=always   -> the user manager relaunches a dead/killed daemon.
  2. Absolute interpreter ExecStart + module form -> no dependence on a `wt`
     shim being on the user manager's minimal PATH.
  3. Environment=PATH -> the daemon can find gh/git/claude/codex.

No real systemctl is invoked: the fixtures point at a temp unit path and either
use an empty config (cmd_install returns before activation) or stub os.system.
"""

from __future__ import annotations

import argparse
import os

import pytest


class _StartArgs:
    foreground = False
    dry_run = False
    interval = 30
    stuck_minutes = 20
    engine = "claude"
    auto_spawn = False
    host = "127.0.0.1"
    port = 8787


@pytest.fixture()
def installed_unit(tmp_path, monkeypatch):
    """Run cmd_install against a temp unit path and an empty config, return the
    written unit text."""
    from watchtower import cli
    from watchtower import config
    from watchtower import skills_sync

    unit_path = tmp_path / "ai.watchtower.watcher.service"
    monkeypatch.setattr(cli, "_SYSTEMD_UNIT", unit_path)
    monkeypatch.setattr(cli, "_use_systemd", lambda: True)
    monkeypatch.setattr(cli, "_is_macos", lambda: False)
    # Empty/nonexistent config -> no drain-on queues -> cmd_install returns
    # before any systemctl call, so the test never shells out.
    monkeypatch.setattr(config, "CONFIG_FILE", tmp_path / "no-config.json")
    monkeypatch.setenv("PATH", "/usr/local/bin:/usr/bin:/bin")
    monkeypatch.setattr(skills_sync, "ENGINE_HOMES", {"claude": tmp_path / "claude-home"})

    rc = cli.cmd_install(argparse.Namespace())
    assert rc == 0
    assert unit_path.exists()
    return unit_path.read_text()


def test_unit_has_required_sections(installed_unit):
    for section in ("[Unit]", "[Service]", "[Install]"):
        assert section in installed_unit


def test_exec_start_absolute_interpreter_and_module(installed_unit):
    line = next(
        l for l in installed_unit.splitlines() if l.startswith("ExecStart=")
    )
    args = line.split("=", 1)[1].split()
    assert args[0].startswith("/"), args
    assert args[1:] == [
        "-m", "watchtower.cli", "start", "--foreground", "--auto-spawn",
    ]
    assert "wt" not in args  # no bare shim


def test_restart_always(installed_unit):
    assert "Restart=always" in installed_unit


def test_environment_path_present(installed_unit):
    line = next(
        l for l in installed_unit.splitlines() if l.startswith("Environment=PATH=")
    )
    path_val = line.split("=", 1)[1]
    assert "/usr/local/bin" in path_val
    assert path_val.endswith("/sbin") or "/usr/sbin" in path_val


def test_starts_on_login(installed_unit):
    assert "WantedBy=default.target" in installed_unit


def test_systemd_available_requires_linux(monkeypatch):
    from watchtower import cli

    monkeypatch.setattr(cli.sys, "platform", "darwin")
    assert cli._systemd_available() is False


def test_systemd_available_requires_marker_dir(monkeypatch):
    from watchtower import cli

    monkeypatch.setattr(cli.sys, "platform", "linux")
    real_isdir = os.path.isdir
    monkeypatch.setattr(cli.os.path, "isdir", lambda p: False if p == "/run/systemd/system" else real_isdir(p))
    monkeypatch.setattr(cli.shutil, "which", lambda name: "/usr/bin/systemctl")
    assert cli._systemd_available() is False


def test_systemd_available_true_with_marker_and_systemctl(monkeypatch):
    from watchtower import cli

    monkeypatch.setattr(cli.sys, "platform", "linux")
    monkeypatch.setattr(cli.os.path, "isdir", lambda p: p == "/run/systemd/system")
    monkeypatch.setattr(cli.shutil, "which", lambda name: "/usr/bin/systemctl")
    assert cli._systemd_available() is True


def test_service_file_none_without_supervisor(monkeypatch):
    from watchtower import cli

    monkeypatch.setattr(cli, "_is_macos", lambda: False)
    monkeypatch.setattr(cli, "_use_systemd", lambda: False)
    assert cli._service_file() is None


def test_start_installs_systemd_unit_when_missing(tmp_path, monkeypatch, capsys):
    """A plain `wt start` with no unit installs it, then activates through
    systemctl. systemctl is stubbed via the os.system seam."""
    from watchtower import cli
    from watchtower import skills_sync

    unit_path = tmp_path / "ai.watchtower.watcher.service"
    monkeypatch.setattr(cli, "_SYSTEMD_UNIT", unit_path)
    monkeypatch.setattr(cli, "_use_systemd", lambda: True)
    monkeypatch.setattr(cli, "_is_macos", lambda: False)
    monkeypatch.setattr(cli, "DAEMON_PID_FILE", tmp_path / "daemon.pid")
    monkeypatch.setattr(cli, "DASHBOARD_PID_FILE", tmp_path / "dashboard.pid")
    monkeypatch.setattr(skills_sync, "ENGINE_HOMES", {"claude": tmp_path / "claude-home"})

    calls = []

    def fake_system(cmd):
        calls.append(cmd)
        return 0

    monkeypatch.setattr(cli.os, "system", fake_system)

    rc = cli.cmd_start(_StartArgs())

    assert rc == 0
    assert unit_path.exists()
    out = capsys.readouterr().out
    assert "first start: installed systemd user service ai.watchtower.watcher.service" in out
    assert any("systemctl --user" in c for c in calls)


def test_stop_uses_systemctl_disable_now(tmp_path, monkeypatch):
    from watchtower import cli

    unit_path = tmp_path / "ai.watchtower.watcher.service"
    unit_path.write_text("[Unit]\n")
    monkeypatch.setattr(cli, "_SYSTEMD_UNIT", unit_path)
    monkeypatch.setattr(cli, "_use_systemd", lambda: True)
    monkeypatch.setattr(cli, "_is_macos", lambda: False)
    monkeypatch.setattr(cli, "DAEMON_PID_FILE", tmp_path / "daemon.pid")

    calls = []
    monkeypatch.setattr(cli.os, "system", lambda cmd: calls.append(cmd) or 0)

    rc = cli.cmd_stop(argparse.Namespace())

    assert rc == 0
    assert any("disable --now" in c for c in calls)
