"""Tests for the hardened LaunchAgent plist generated by `wt install`.

These lock in the three reliability fixes so a future `wt install` reproduces a
correctly supervised daemon:
  1. KeepAlive=true  -> launchd relaunches a dead/killed daemon.
  2. Absolute interpreter in ProgramArguments + module form -> no dependence on a
     `wt` shim being on launchd's minimal PATH.
  3. EnvironmentVariables PATH -> the daemon can find gh/git/claude/codex.

No launchctl is invoked: we point config at an empty path so cmd_install returns
before the conditional `launchctl load`.
"""

from __future__ import annotations

import argparse

import pytest


@pytest.fixture()
def installed_plist(tmp_path, monkeypatch):
    """Run cmd_install against a temp plist path and an empty config, return the
    written plist text."""
    from watchtower import cli
    from watchtower import config
    from watchtower import skills_sync

    plist_path = tmp_path / "ai.watchtower.watcher.plist"
    monkeypatch.setattr(cli, "_LAUNCHAGENT_PLIST", plist_path)
    # Empty/nonexistent config -> no drain-on queues -> cmd_install returns
    # before any launchctl load, so the test never shells out.
    monkeypatch.setattr(config, "CONFIG_FILE", tmp_path / "no-config.json")
    # Make PATH deterministic and include a homebrew-like dir to assert on.
    monkeypatch.setenv("PATH", "/opt/homebrew/bin:/usr/bin:/bin")
    # cmd_install also syncs the bundled skill -- point it at a scratch
    # "harness home" so the test never touches the real ~/.claude or ~/.codex.
    monkeypatch.setattr(skills_sync, "ENGINE_HOMES", {"claude": tmp_path / "claude-home"})

    rc = cli.cmd_install(argparse.Namespace())
    assert rc == 0
    assert plist_path.exists()
    return plist_path.read_text()


def test_keepalive_is_true(installed_plist):
    # launchd must relaunch a dead or killed daemon.
    assert "<key>KeepAlive</key>" in installed_plist
    ka = installed_plist.split("<key>KeepAlive</key>", 1)[1]
    assert ka.lstrip().startswith("<true/>")
    assert "<false/>" not in installed_plist  # no stray false left behind


def test_run_at_load_is_true(installed_plist):
    assert "<key>RunAtLoad</key>" in installed_plist
    ral = installed_plist.split("<key>RunAtLoad</key>", 1)[1]
    assert ral.lstrip().startswith("<true/>")


def test_program_arguments_use_absolute_interpreter_and_module(installed_plist):
    # First ProgramArguments entry must be an absolute path (the interpreter),
    # not a bare `wt` shim that launchd's minimal PATH cannot resolve.
    body = installed_plist.split("<key>ProgramArguments</key>", 1)[1]
    array = body.split("<array>", 1)[1].split("</array>", 1)[0]
    strings = [
        s.split("</string>", 1)[0]
        for s in array.split("<string>")[1:]
    ]
    assert strings[0].startswith("/"), strings
    assert strings != []
    # Module invocation form: -m watchtower.cli start --foreground --auto-spawn
    assert "-m" in strings
    assert "watchtower.cli" in strings
    assert "start" in strings
    assert "--foreground" in strings
    assert "--auto-spawn" in strings
    assert "wt" not in strings  # no bare shim


def test_environment_variables_path_present(installed_plist):
    assert "<key>EnvironmentVariables</key>" in installed_plist
    env = installed_plist.split("<key>EnvironmentVariables</key>", 1)[1]
    assert "<key>PATH</key>" in env
    path_val = env.split("<key>PATH</key>", 1)[1].split("<string>", 1)[1]
    path_val = path_val.split("</string>", 1)[0]
    # The daemon shells out to homebrew + user-local tools.
    assert "/opt/homebrew/bin" in path_val
    assert path_val.endswith("/sbin") or "/usr/sbin" in path_val


def test_launchd_path_prepends_and_dedupes(monkeypatch):
    from watchtower import cli

    monkeypatch.setenv("PATH", "/opt/homebrew/bin:/some/custom/bin")
    path = cli._launchd_path()
    parts = path.split(":")
    # Homebrew + user-local + custom + system dirs, all present, no dupes.
    assert "/opt/homebrew/bin" in parts
    assert "/usr/local/bin" in parts
    assert "/some/custom/bin" in parts
    for sysdir in ("/usr/bin", "/bin", "/usr/sbin", "/sbin"):
        assert sysdir in parts
    assert len(parts) == len(set(parts)), path
    # user-local bin should be prepended (appears before the custom entry).
    home_local = f"{cli.os.path.expanduser('~/.local/bin')}"
    assert parts.index(home_local) < parts.index("/some/custom/bin")


# --------------------------------------------------------- wt start auto-install
# `wt start` folds `wt install` into itself on first run (Change 1): a plain
# `wt start` with no plist installs it, then continues into the launchd-start
# path. `--foreground` (what the plist itself execs) and `--dry-run` must
# never install, since neither has a real user session / should touch disk.


class _StartArgs:
    """Minimal cmd_start Namespace stand-in; override per test."""
    foreground = False
    dry_run = False
    interval = 30
    stuck_minutes = 20
    engine = "claude"
    auto_spawn = False
    host = "127.0.0.1"
    port = 8787


@pytest.fixture()
def start_env(tmp_path, monkeypatch):
    """Same plist-test isolation pattern as `installed_plist` above, extended
    to the daemon/dashboard pidfiles `wt start` touches."""
    from watchtower import cli
    from watchtower import config
    from watchtower import skills_sync

    plist_path = tmp_path / "ai.watchtower.watcher.plist"
    monkeypatch.setattr(cli, "_LAUNCHAGENT_PLIST", plist_path)
    monkeypatch.setattr(config, "CONFIG_FILE", tmp_path / "no-config.json")
    monkeypatch.setenv("PATH", "/opt/homebrew/bin:/usr/bin:/bin")
    monkeypatch.setattr(skills_sync, "ENGINE_HOMES", {"claude": tmp_path / "claude-home"})
    monkeypatch.setattr(cli, "DAEMON_PID_FILE", tmp_path / "daemon.pid")
    monkeypatch.setattr(cli, "DASHBOARD_PID_FILE", tmp_path / "dashboard.pid")
    return cli, plist_path


def test_start_installs_plist_when_missing(start_env, monkeypatch, capsys):
    """A plain `wt start` with no LaunchAgent installed writes the plist (and
    prints a one-line notice) before continuing into the launchd-start path.
    launchctl itself is stubbed out -- this test only asserts the install."""
    cli, plist_path = start_env
    assert not plist_path.exists()
    monkeypatch.setattr(cli.os, "system", lambda cmd: 0)

    rc = cli.cmd_start(_StartArgs())

    assert rc == 0
    assert plist_path.exists()
    out = capsys.readouterr().out
    assert "first start: installed LaunchAgent ai.watchtower.watcher" in out


def test_start_foreground_never_installs(start_env, monkeypatch):
    """`--foreground` is what the plist itself execs (no user session); it
    must never try to install, or a first boot would recurse forever."""
    cli, plist_path = start_env
    monkeypatch.setattr(cli, "_daemon_loop", lambda args: None)

    class Args(_StartArgs):
        foreground = True

    assert not plist_path.exists()
    rc = cli.cmd_start(Args())

    assert rc == 0
    assert not plist_path.exists()


def test_start_dry_run_writes_nothing(start_env, monkeypatch):
    """`--dry-run` is a pure in-process run; it must not write the plist or
    any other state."""
    cli, plist_path = start_env
    monkeypatch.setattr(cli, "_daemon_loop", lambda args: None)

    class Args(_StartArgs):
        dry_run = True

    assert not plist_path.exists()
    rc = cli.cmd_start(Args())

    assert rc == 0
    assert not plist_path.exists()
    assert not cli.DAEMON_PID_FILE.exists()
